Feature/cache config endpoint
aservo/confapi-confluence-plugin pull request #67
Opened 2020-11-19 07:52 UTC by mbrowars

2020-11-23 12:06 UTC, pathob requested changes

2020-11-23 12:06 UTC, pathob commented on src/test/java/de/aservo/confapi/confluence/service/CachesServiceTest.java
> +        assertEquals(cachesService.getAllCaches().iterator().next(), CacheBeanUtil.toCacheBean(cache));
`doReturn(...).when(...)...` hat sich bei uns als robuster erwiesen, deswegen sollte `when(...).thenReturn(...)` nicht mehr genutzt werden.

2020-11-23 12:06 UTC, pathob commented on src/test/java/de/aservo/confapi/confluence/service/CachesServiceTest.java
> +
Sollte ebenfalls nicht benötigt werden, da ja schon vorher die Exception fliegt

2020-11-23 12:06 UTC, pathob commented on src/test/java/de/aservo/confapi/confluence/service/CachesServiceTest.java
> +        verify(cache).clear();
Ebenfalls nicht benötigt

2020-11-23 14:06 UTC, mbrowars commented on src/test/java/de/aservo/confapi/confluence/service/CachesServiceTest.java
> +        verify(cache).clear();
geht es hier nur um das verify? die anderen Sachen benötige ich schon, damit überhaupt ein Cache gefunden wird ( der flushable ist).

2020-11-23 14:24 UTC, mbrowars commented on src/main/java/de/aservo/confapi/confluence/model/CacheBean.java
> +    private Integer maxObjectSize;
Vorschlag: **maxObjectCount** passt eher als size.

2020-11-24 03:31 UTC, pathob commented on src/main/java/de/aservo/confapi/confluence/model/CacheBean.java
> +    private Integer maxObjectSize;
Finde ich ich besser. Klingt sonst eher als ginge es um die Größe der Objekte, nicht um die Anzahl

2020-12-01 04:42 UTC, pathob requested changes
Hi @mbrowars Es gibt leider doch noch einen Bug, den bitte nochmal nachbessern. Und da du eh nachbessern musst, habe ich mir nochmal erlaubt, um eine kleine Anpassung beim REST Endpoint zu bitten.

2020-12-01 04:42 UTC, pathob commented on src/main/java/de/aservo/confapi/confluence/model/CachesBean.java
> +    private Collection<GadgetBean> gadgets;
Hier ist doch noch etwas schiefgegangen.

2020-12-01 04:42 UTC, pathob commented on src/main/java/de/aservo/confapi/confluence/rest/api/CachesResource.java
> +    @Path(ConfAPI.CACHE_FLUSH + "/{name}")
Hier wäre `@Path("{name}/" + ConfAPI.CACHE_FLUSH)` Eigentlich sogar schöner, weil der Identifier dann bei allen Methoden an derselben Stelle steht.

2020-12-01 04:42 UTC, pathob commented on src/main/java/de/aservo/confapi/confluence/service/CachesServiceImpl.java
> +    }
Deswegen ist das mit dem CachesBean nicht aufgefallen. Du kannst hier einfach das `new CachesBean(...)` um den Stream herum packen :)

2020-12-01 04:42 UTC, pathob commented on src/main/java/de/aservo/confapi/confluence/service/api/CachesService.java
> +    Collection<CacheBean> getAllCaches();
Dito

2020-12-02 08:52 UTC, pathob submitted a review, later dismissed

2020-12-03 08:49 UTC, mbrowars commented on src/main/java/de/aservo/confapi/confluence/rest/api/CachesResource.java
> +            summary = "Update an existing cache-size",
Hinweis ergänzt.

2020-12-03 09:21 UTC, lehmannk approved these changes

2020-12-03 09:28 UTC, merged