Removed bug discarding all gadgets as invalid.
aservo/confapi-confluence-plugin pull request #73
Opened 2021-04-13 22:10 UTC by cosminvlaicu

addGadget method in GadgetServiceImpl always throws error for totally valid gadgets even for a clean instance. The method can add gadgets only after successfully adding the same gadget on the web UI. 

Workaround:
Moved the check for valid gadget URL after adding the gadget, and deleting the gadget at the end if invalid.

2021-04-14 15:51 UTC, lehmannk submitted a review, later dismissed
OK, sieht gut aus. Muss wohl ein Sonderfall sein, wenn noch keine Gadgets vorhanden waren, da verhält sich Confluence merkwürdig. Wenn du es so auch erfolgreich getestest hast dann kann das gemergt werden.

2021-04-15 07:40 UTC, pathob requested changes

2021-04-15 07:40 UTC, pathob commented on src/main/java/de/aservo/confapi/confluence/service/GadgetsServiceImpl.java
> +            throw new GadgetParsingException("Invalid Gadget URL");
BadRequestException

2021-04-15 09:02 UTC, pathob approved these changes

2021-04-15 09:02 UTC, merged